spring.application.name=asset-manager

spring.datasource.url=jdbc:mysql://localhost:3306/asset_db?characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=27Feb2004!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true